"""
Search & sharing for Bohemia: page titles, link previews, residence addresses, sitemap.

    python tools/build_pages.py

Reads the domain from tools/site.json and the content from js/data.js, then writes:
  - the <!-- seo --> block in index.html and residence.html (title, description, canonical,
    EN/PT alternates, Open Graph / WhatsApp preview tags)
  - garden.html and penthouse.html (one per residence in data.js): copies of residence.html with
    their own preview tags, so a forwarded link shows that residence. Served as /garden, /penthouse
    on Vercel (vercel.json cleanUrls) and Netlify.
  - assets/share/*.jpg (1200 x 630 preview pictures)
  - sitemap.xml and robots.txt

Run it again after changing the domain, residence.html, or a residence's name, facts or pictures.
Requires: Node (to read js/data.js) and Pillow.
"""
import html, json, re, subprocess, sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SITE = json.loads((ROOT / 'tools' / 'site.json').read_text(encoding='utf-8'))
DOMAIN = SITE['domain'].rstrip('/')
BLOCK = re.compile(r'  <!-- seo:[^\n]*-->\n.*?  <!-- /seo -->\n', re.S)


def load_data():
    js = "globalThis.window=globalThis;require(process.argv[1]);process.stdout.write(JSON.stringify({B:window.BOHEMIA,I:window.I18N}))"
    out = subprocess.run(['node', '-e', js, str(ROOT / 'js' / 'data.js')], capture_output=True, text=True, encoding='utf-8', check=True)
    d = json.loads(out.stdout)
    return d['B'], d['I']


def share_image(name, src):
    """1200 x 630 JPEG for link previews, cropped from the best available render."""
    out = ROOT / 'assets' / 'share' / (name + '.jpg')
    out.parent.mkdir(exist_ok=True)
    big = ROOT / 'assets' / 'img' / (src + '-4k.webp')
    path = big if big.exists() else ROOT / 'assets' / 'img' / (src + '.webp')
    im = Image.open(path).convert('RGB')
    w, h = im.size
    tw = min(w, int(h * 1200 / 630)); th = int(tw * 630 / 1200)
    left, top = (w - tw) // 2, (h - th) // 2
    im.crop((left, top, left + tw, top + th)).resize((1200, 630), Image.LANCZOS).save(out, 'JPEG', quality=82, optimize=True, progressive=True)
    return 'assets/share/' + name + '.jpg'


def block(title, desc, path, image, index=True):
    e = lambda s: html.escape(s, quote=True)
    url = DOMAIN + path
    alt = url + ('&' if '?' in url else '?') + 'lang=pt'
    lines = ['  <!-- seo: generated by tools/build_pages.py (edit there, not here) -->',
             f'  <title>{e(title)}</title>',
             f'  <meta name="description" content="{e(desc)}">']
    if index:
        lines += [f'  <link rel="canonical" href="{e(url)}">',
                  f'  <link rel="alternate" hreflang="en" href="{e(url)}">',
                  f'  <link rel="alternate" hreflang="pt" href="{e(alt)}">',
                  f'  <link rel="alternate" hreflang="x-default" href="{e(url)}">']
    else:
        lines += ['  <meta name="robots" content="noindex, follow">']
    lines += ['  <meta property="og:type" content="website">',
              '  <meta property="og:site_name" content="Bohemia">',
              f'  <meta property="og:title" content="{e(title)}">',
              f'  <meta property="og:description" content="{e(desc)}">',
              f'  <meta property="og:url" content="{e(url)}">',
              f'  <meta property="og:image" content="{e(DOMAIN + "/" + image)}">',
              '  <meta property="og:image:width" content="1200">',
              '  <meta property="og:image:height" content="630">',
              '  <meta property="og:locale" content="en_GB">',
              '  <meta property="og:locale:alternate" content="pt_PT">',
              '  <meta name="twitter:card" content="summary_large_image">',
              '  <!-- /seo -->']
    return '\n'.join(lines) + '\n'


def put_block(text, new, page):
    if not BLOCK.search(text):
        sys.exit(f'{page}: no <!-- seo --> block found')
    return BLOCK.sub(lambda m: new, text, count=1)


def residence_desc(u, I):
    outs = [o['k'] for o in u['outdoor'] if o['k'] != 'pool']
    has_pool = any(o['k'] == 'pool' for o in u['outdoor'])
    def joined(lang, last):
        names = [I[lang]['room.' + k].lower() for k in outs] + ([last] if has_pool else [])
        return ', '.join(names[:-1]) + (' ' + ('and' if lang == 'en' else 'e') + ' ' if len(names) > 1 else '') + names[-1]
    en = f"{u['bedrooms']} suites · {joined('en', 'private pool')} · Avenida da Dinamarca, Estoril."
    ty = (u.get('typology') or {}).get('pt') or f"T{u['bedrooms']}"
    pt = f"{ty} · {joined('pt', 'piscina privativa')}."
    return en + ' ' + pt


def main():
    B, I = load_data()
    if 'YOUR-DOMAIN' in DOMAIN:
        print('NOTE: tools/site.json still has the placeholder domain; previews only work once it is set.')

    # homepage
    p = ROOT / 'index.html'
    desc = ('Two exceptional residences on Avenida da Dinamarca, Estoril, by Bohemian Group. '
            'Duas residências excecionais na Avenida da Dinamarca, Estoril.')
    img = share_image('home', 'ext-angle')
    p.write_text(put_block(p.read_text(encoding='utf-8'), block('Bohemia — Private Residences, Estoril', desc, '/', img), 'index.html'), encoding='utf-8', newline='\n')

    # residence template (residence.html?r=…): kept working, but not indexed
    p = ROOT / 'residence.html'
    tpl = put_block(p.read_text(encoding='utf-8'),
                    block('Residence — Bohemia, Estoril', 'A residence at Bohemia, Avenida da Dinamarca, Estoril.', '/residence.html', img, index=False),
                    'residence.html')
    p.write_text(tpl, encoding='utf-8', newline='\n')

    # one page per residence
    urls = ['/']
    for u in B['units']:
        img = share_image(u['id'], u['cover'])
        title = u['name']['en'] + ' — Bohemia, Estoril'
        page = put_block(tpl, block(title, residence_desc(u, I), '/' + u['id'], img), u['id'])
        page = page.replace('<body>', f'<body data-residence="{u["id"]}">', 1)
        page = page.replace('<html lang="en">', '<html lang="en">\n<!-- generated from residence.html by tools/build_pages.py: edit residence.html, then re-run -->', 1)
        (ROOT / (u['id'] + '.html')).write_text(page, encoding='utf-8', newline='\n')
        urls.append('/' + u['id'])
        print('wrote', u['id'] + '.html')

    # sitemap + robots
    sm = ['<?xml version="1.0" encoding="UTF-8"?>',
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">']
    for path in urls:
        loc = DOMAIN + path
        pt = loc + ('&' if '?' in loc else '?') + 'lang=pt'
        for here in (loc, pt):
            sm += ['  <url>', f'    <loc>{html.escape(here)}</loc>',
                   f'    <xhtml:link rel="alternate" hreflang="en" href="{html.escape(loc)}"/>',
                   f'    <xhtml:link rel="alternate" hreflang="pt" href="{html.escape(pt)}"/>', '  </url>']
    sm.append('</urlset>')
    (ROOT / 'sitemap.xml').write_text('\n'.join(sm) + '\n', encoding='utf-8', newline='\n')
    (ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /dist/\nDisallow: /tools/\n\n'
                                     f'Sitemap: {DOMAIN}/sitemap.xml\n', encoding='utf-8', newline='\n')
    print('wrote index.html / residence.html seo blocks, sitemap.xml, robots.txt, assets/share/*.jpg')


if __name__ == '__main__':
    main()
